cheking_orders/cheking_orders/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cheking_orders/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    # страница с тремя ссылками -
    # годы/загрузка/выгрузка (только авторизированным всё).
    path('', views.index, name='index'),
    # страница со списком годов и статусом года (done/ not done)
    path('years/', views.years_list, name='years_list'),
    # Отдельная страница с информацией о конкретном годе
    # и статусом месяца (done/ not done)
    path('years/<int:year>/', views.months_list, name='months_list'),
    # страница со списком заказов за месяц и статусом заказов (done/ not done)
    path('years/<int:year>/<int:month>/',
         views.month_list_orders,
         name='month_list_orders'),
    # страница с тремя полями для загрузки данных
    # СКД/Али/Претензия
    path('upload/', views.upload, name='upload'),
    # страница с фильтром данных и выгрузкой данных по филтру
    # поля фильтра год/все месяцы или конкретный/статус заказов все или нет
    path('download/', views.download, name='download'),
    path('upload/upload_vendor/', views.upload_vendor, name='upload_vendor'),
    path('upload/upload_market/', views.upload_market, name='upload_market'),
    path('upload/upload_return/', views.upload_return, name='upload_return'),
    path('upload/upload_claim/', views.upload_claim, name='upload_claim'),
]

cheking_orders/orders/models.py
from django.db import models


class Orders_vendor(models.Model):
    """Данная модель хранит заказы по версии поставщика"""
    order = models.BigIntegerField(
        primary_key=True,
        verbose_name='Номер заказа')
    # Необходима проверка на мин и макс значения
    month_of_order = models.IntegerField(
        verbose_name='Месяц'
    )
    # Необходима проверка на мин и макс значения
    year_of_order = models.IntegerField(
        verbose_name='Год'
    )
    sale_price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='РРЦ вендор')
    shipping_price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='Отгрузка вендор')

    def order_status(self):
        # Проверяем статус заказа
        if Orders_on_claim.objects.filter(
                    order__exact=self.order).exists():
            status_order = 'Учтено в претензии'
            return status_order
        elif Return_order.objects.filter(
                    order__exact=self.order).exists():
            status_order = 'Есть возврат'
            return status_order
        elif Orders_market.objects.filter(
                    order__exact=self.order).exists():
            status_order = 'Учтено в маркетплейсе'
            return status_order
        else:
            status_order = 'Не учтено в маркетплейсе'
            return status_order

    def order_summ(self):
        # Проверяем расхождения в цене
        market_order = Orders_market.objects.filter(order__exact=self.order)
        vendor_sp = self.sale_price
        vendor_shp = self.shipping_price
        market_sp = market_order.sale_price_market
        market_shp = market_sp - market_order.shipping_price_market
        sp_result = vendor_sp - market_sp
        shp_result = vendor_shp - market_shp
        if sp_result and shp_result != 0:
            price_status = 'Есть расхождения в цене'
            return price_status
        price_status = 'Нет расхождений в цене'
        return price_status


class Orders_market(models.Model):
    """Данная модель хранит заказы по версии маркетплейс"""
    order = models.ForeignKey(Orders_vendor, on_delete=models.CASCADE)
    sale_price_market = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='РРЦ маркетплейс')
    shipping_price_market = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='Отгрузка маркетплейс')
    # Необходима проверка на мин и макс значения
    month_of_order_market = models.IntegerField(
        verbose_name='Месяц маркетплейс'
    )
    # Необходима проверка на мин и макс значения
    year_of_order_market = models.IntegerField(
        verbose_name='Год маркетплейс'
    )


class Return_order(models.Model):
    """Данная модель хранит заказы попавшие в возвраты"""
    """в документах маркетплейса."""
    order = models.ForeignKey(Orders_vendor, on_delete=models.CASCADE)
    month_of_return = models.IntegerField(
        verbose_name='Месяц в документах которого маркетплейс учел возврат'
    )
    # Необходима проверка на отрицательное число
    sale_price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='Сумма возврата итого по заказу')


class Orders_on_claim(models.Model):
    """Данная модель хранит заказы возмещенные маркетплейсом."""
    order = models.ForeignKey(Orders_vendor, on_delete=models.CASCADE)
    was_paid_for_return = models.BooleanField(
        verbose_name='Возврат в претензии')
    date_of_claim = models.DateField(
        auto_now=False,
        auto_now_add=False,
        verbose_name='Дата претензии')


class Csv(models.Model):
    file_name = models.FileField(upload_to='csvs')
    uploaded = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)

    def __str__(self):
        return f'File id: {self.id}'

cheking_orders/orders/forms.py
from django import forms
from .models import (Orders_vendor,
                     Orders_market,
                     Return_order,
                     Orders_on_claim,
                     Csv
                     )


class Orders_vendorForm(forms.ModelForm):
    class Meta:
        model = Orders_vendor
        fields = ('order',
                  'month_of_order',
                  'year_of_order',
                  'sale_price',
                  'shipping_price')


class Orders_marketForm(forms.ModelForm):
    class Meta:
        model = Orders_market
        fields = ('order',
                  'sale_price_market',
                  'shipping_price_market',
                  'month_of_order_market',
                  'year_of_order_market')


class Return_orderForm(forms.ModelForm):
    class Meta:
        model = Return_order
        fields = ('order',
                  'month_of_return',
                  'sale_price',)


class Orders_on_claimForm(forms.ModelForm):
    class Meta:
        model = Orders_on_claim
        fields = ('order',
                  'was_paid_for_return',
                  'date_of_claim',)


class CsvForm(forms.ModelForm):
    class Meta:
        model = Csv
        fields = ('file_name',)

cheking_orders/orders/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import (Orders_vendor,
                     Orders_market,
                     Return_order,
                     Orders_on_claim,
                     Csv
                     )
from django.shortcuts import get_object_or_404, redirect
from cheking_orders.settings import MONTHS, YEARS
from .forms import (Orders_marketForm,
                    Orders_vendorForm,
                    Orders_on_claimForm,
                    Return_orderForm,
                    CsvForm
                    )
import csv


def month_status(month, year):
    orders = Orders_vendor.objects.filter(
        year_of_order=year,
        month_of_order=month)
    status_all = []
    for i in orders:
        status = i.order_status()
        if status not in status_all:
            status_all.append(status)

    return status_all


def index(request):
    template = 'orders/index.html'
    return render(request, template)


def years_list(request):
    template = 'orders/years_list.html'
    context = {
        'years': YEARS,
    }
    return render(request, template, context)


def months_list(request, year):
    template = 'orders/months_list.html'
    for month in MONTHS:
        status = month_status(month, year)

    context = {
        'status': status,
        'months': MONTHS,
        'year': year,
    }
    return render(request, template, context)


def month_list_orders(request, year, month):
    template = 'orders/month_list_orders.html'
    orders = Orders_vendor.objects.filter(
        year_of_order=year,
        month_of_order=month)
    context = {
        'orders': orders,
    }
    return render(request, template, context)


def upload(request):
    template = 'orders/upload.html'
    return render(request, template)


def upload_vendor(request):
    form = CsvForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = CsvForm()
        obj = Csv.objects.get(activated=False)
        with open(obj.file_name.path, 'r') as f:
            reader = csv.reader(f)
            for row in reader:
                row = ''.join(row)
                row = row.replace(';', ' ')
                row = row.split()
                order = int(row[0])
                month_of_order = int(row[1])
                year_of_order = int(row[2])
                sale_price = float(row[3])
                shipping_price = float(row[4])
                Orders_vendor.objects.get_or_create(
                    order=order,
                    month_of_order=month_of_order,
                    year_of_order=year_of_order,
                    sale_price=sale_price,
                    shipping_price=shipping_price,
                    )
        obj.activated = True
        obj.save()
    template = 'orders/uploadvendor.html'
    return render(request, template, {'form': form})


def upload_market(request):
    form = CsvForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = CsvForm()
        obj = Csv.objects.get(activated=False)
        with open(obj.file_name.path, 'r') as f:
            reader = csv.reader(f)
            for row in reader:
                row = ''.join(row)
                row = row.replace(';', ' ')
                row = row.split()
                order = int(row[0])
                month_of_order_market = int(row[1])
                year_of_order_market = int(row[2])
                sale_price_market = float(row[3])
                shipping_price_market = float(row[4])
                Orders_market.objects.get_or_create(
                    order=order,
                    month_of_order_market=month_of_order_market,
                    year_of_order_market=year_of_order_market,
                    sale_price_market=sale_price_market,
                    shipping_price_market=shipping_price_market,
                    )
        obj.activated = True
        obj.save()
    template = 'orders/uploadmarket.html'
    return render(request, template, {'form': form})


def upload_return(request):
    template = 'orders/upload.html'
    return render(request, template)


def upload_claim(request):
    template = 'orders/upload.html'
    return render(request, template)


def download(request):
    pass

cheking_orders/templates/orders/index.html
{% extends 'base.html' %}
{% block title %}
    Проверка статуса заказов
{% endblock %}
{% block content %}
<div class="row row-cols-1 row-cols-md-3" style="top: 200px;">
    <div class="card-deck">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Просмотр данных по периодам</h5>
          <p class="card-text">Далее доступна общая информация по периодам.</p>
          <a href="{% url 'orders:years_list' %}" class="btn btn-primary">Выбрать период</a>
        </div>
      </div>
    </div>
    <div class="card-deck">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Загрузка данных</h5>
          <p class="card-text">Для загрузки данных приведите данные к требуемым форматам.</p>
          <a href="{% url 'orders:upload' %}" class="btn btn-primary">Загрузить данные</a>
        </div>
      </div>
    </div>
    <div class="card-deck">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Работа с данными</h5>
            <p class="card-text">Выгрузка данных доступно по фильтру и без.</p>
            <a href="{% url 'orders:download' %}" class="btn btn-primary">Выгрузить данные</a>
          </div>
        </div>
    </div>
</div> 
{% endblock %}  

cheking_orders/templates/orders/month_list_orders.html
{% extends 'base.html' %}
{% block title %}
Просмотр данных по периодам
{% endblock %}
{% block content %}
    {% for order in orders %}
    {% include 'includes/order.html' %}
    {%endfor%}
 
{% endblock %}  

cheking_orders/templates/orders/months_list.html
{% extends 'base.html' %}
{% block title %}
Просмотр данных по периодам
{% endblock %}
{% block content %}
<div class="row row-cols-1 row-cols-md-3" style="top: 200px;">
    {% for month in months %}
    <div class="card-deck">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{month}}</h5>
          <p class="card-text">Статус месяца:{{status}} .</p>
          <a href="{% url 'orders:month_list_orders' year month %}" class="btn btn-primary">Открыть</a>
        </div>
      </div>
    </div>
    {%endfor%}
 
{% endblock %}  

cheking_orders/templates/orders/upload.html
{% extends 'base.html' %}
{% block title %}
    Выберите тип данных для загрузки
{% endblock %}
{% block content %}
<div class="row row-cols-1 row-cols-md-3" style="top: 200px;">
    <div class="card-deck">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Загрузка данных Вендор</h5>
          
          <a href="{% url 'orders:upload_vendor' %}" class="btn btn-primary">Перейти</a>
        </div>
      </div>
    </div>
    <div class="card-deck">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Загрузка данных Маркет</h5>
          
          <a href="{% url 'orders:upload_market' %}" class="btn btn-primary">Перейти</a>
        </div>
      </div>
    </div>
    <div class="card-deck">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Загрузка данных Возвраты</h5>
            
            <a href="{% url 'orders:upload_return' %}" class="btn btn-primary">Перейти</a>
          </div>
        </div>
    </div>
    <div class="card-deck">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Загрузка данных Претензии</h5>
            
            <a href="{% url 'orders:upload_claim' %}" class="btn btn-primary">Перейти</a>
          </div>
        </div>
    </div>
</div> 
{% endblock %}  

cheking_orders/templates/orders/uploadmarket.html
{% extends 'base.html' %}
{% block title %}
Загрузка данных
{% endblock %}
{% block content %}
<div class="card">
<form action="{% url "orders:upload_market" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
    {% csrf_token %}
        {{form}}
    <div class="form-group">                    
        <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
             <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
        </div> 
    </div>
    </form>
</div>
{% endblock %} 

cheking_orders/templates/orders/uploadvendor.html
{% extends 'base.html' %}
{% block title %}
Загрузка данных
{% endblock %}
{% block content %}
<div class="card">
<form action="{% url "orders:upload_vendor" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
    {% csrf_token %}
        {{form}}
    <div class="form-group">                    
        <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
             <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
        </div> 
    </div>
    </form>
</div>
{% endblock %} 

cheking_orders/templates/orders/years_list.html
{% extends 'base.html' %}
{% block title %}
Просмотр данных по периодам
{% endblock %}
{% block content %}
<div class="row row-cols-1 row-cols-md-3" style="top: 200px;">
    {% for year in years %}
    <div class="card-deck">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{year}}</h5>
          <p class="card-text">Далее доступна подробная информация по месяцам.</p>
          <a href="{% url 'orders:months_list' year %}" class="btn btn-primary">Открыть</a>
        </div>
      </div>
    </div>
    {%endfor%}
 
{% endblock %}  